### ISSUE TITLE
Button tooltips

### ISSUE THREAD

**Issue by neodescis** [watergis/maplibre-gl-terradraw#38]
It would be great if the buttons had tooltip support. Some of them are obvious, but not all of them. We have tooltips on our other map controls, so consistency would be great.

**Comment by JinIgarashi** [comment]
@neodescis I agree. What texts for each button do you suggest for tooltips?

**Comment by neodescis** [comment]
I think just the names of the shapes would be appropriate, e.g. "Angled Rectangle", "Point", etc.
