### ISSUE TITLE
Always-Open mode

### ISSUE THREAD

**Issue by neodescis** [watergis/maplibre-gl-terradraw#39]
It would be nice to be able to specify in the API that the controls should always be expanded, and hide the button to collapse them.

**Comment by JinIgarashi** [comment]
@neodescis there is `open` option to expand tool as default.

https://github.com/watergis/maplibre-gl-terradraw/blob/f4231f021632c872eb21596707a90c46fa1b4c1b/src/lib/interfaces/ControlOptions.ts#L17-L20

I will close this issue. feel free to reopen if necessary

**Comment by neodescis** [comment]
Yes, but I meant that an always-open mode would also hide the button to collapse the menu.
