### ISSUE TITLE
Delete button: clear only selected shapes?

### ISSUE THREAD

**Issue by neodescis** [watergis/maplibre-gl-terradraw#40]
In my opinion, the delete button should only remove currently selected shapes. I was somewhat surprised when I clicked the button and everything disappeared. Maybe this could be configurable?

**Comment by JinIgarashi** [comment]
@neodescis currently, delete button clear all geometries. This is default behaviour of terradraw. I agree that deleting only selected feature is needed. I am not sure how I can implement that...still thinking how to implement

**Comment by JinIgarashi** [comment]
@neodescis I added `delete-selection` mode to only delete selected feature.
