### ISSUE TITLE
Angled Rectangle button rotated weirdly

### ISSUE THREAD

**Issue by neodescis** [watergis/maplibre-gl-terradraw#41]
![image](https://github.com/user-attachments/assets/b42ba056-d210-459e-9b8c-94353d4407b9)

It seems that the entire Angled Rectangle button is rotated, instead of just its icon.

**Comment by JinIgarashi** [comment]
@neodescis I agree some of icons are not appropriate. I was struggling icons to differentiate polygon, rectangle and angled-rectangle. Because the term of `angled`, I just put rotated rectangle icon for it.

What icon would be better for angled-rectangle? Do you have any idea?

**Comment by neodescis** [comment]
Actually I think the icon is fine! I would just rotate only the icon though, and not the entire button.
