### ISSUE TITLE
remove controlContainer from partent when calling onRemove()

### ISSUE THREAD

**Issue by Simomson** [watergis/maplibre-gl-terradraw#54]
Hi,
First of all, thank you for this package!

After running `map.removeControl(drawControl)` the controlContainer still exists and is visible. 
If I am not mistaken, we can just remove it as shown below:

```diff
diff --git a/node_modules/@watergis/maplibre-gl-terradraw/dist/maplibre-gl-terradraw.es.js b/node_modules/@watergis/maplibre-gl-terradraw/dist/maplibre-gl-terradraw.es.js
index a4839f6..25b5b55 100644
--- a/node_modules/@watergis/maplibre-gl-terradraw/dist/maplibre-gl-terradraw.es.js
+++ b/node_modules/@watergis/maplibre-gl-terradraw/dist/maplibre-gl-terradraw.es.js
@@ -2695,7 +2695,7 @@ class He {
     }), this.controlContainer;
   }
   onRemove() {
-    !this.controlContainer || !this.controlContainer.parentNode || !this.map || (this.modeButtons = {}, this.terradraw = void 0, this.map = void 0);
+    !this.controlContainer || !this.controlContainer.parentNode || !this.map || (this.modeButtons = {}, this.terradraw = void 0, this.map = void 0, this.controlContainer.parentNode.removeChild(this.controlContainer));
   }
   /**
    * Activate Terra Draw to start drawing
```

If you want, I can open a pull request with this change.

**Comment by ncuthbert** [comment]
This was just what I was looking for! Works perfectly👌 
Thanks @Simomson

**Comment by JinIgarashi** [comment]
Thanks @Simomson for reporting the bug. if you can make a PR to fix it, it would be helpful

**Comment by Simomson** [comment]
hey @JinIgarashi ,
A little unfortunate timing and oversight from my side: I just realized that the created layers and the shapes stay and don't get removed. 
I am guessing the expected behaviour would be removing the layers from the map(?).
I am not familiar with TerraDraw. If we can just remove the layers (their sources with the same name) 'td-linestring', 'td-polygon', 'td-polygon-outline', and 'td-point', I will create a new issue and PR.
